//MongoDB System schema for storing in Database

var mongoose = require('mongoose');

var SystemSchema = new mongoose.Schema({
  companyName: String,
  systemName: String,
  serialNumber: String,
  productFamily: String,
  model: String,
  osVersion: String,
  patches: String,
  cpgCount: String,
  recommendedOsVersion: String,
  locationRegion: String,
  locationCountry: String,
  installDate: String,
  updated: String,
  capacityTotalFreePct: String,
  capacityTotalFreeTiB: String,
  capacityTotalSizeTiB: String,
  capacityTotalDedupeRatio: String,
  nodeCount: String,
  nodeCountOffline: String,
  totalDiskCount: String,
  totalDiskCountNormal: String,
  totalDiskCountDegraded: String,
  totalDiskCountFailed: String,
  contractStartDate: String,
  contractEndDate: String,
  batteryExpiry: String,
  spVersion: String,
  vvCount: String,
  tdvvSizeTiB: String,
  dataRateKBPSAvg: String,
  iopsAvg: String,
  iopsMax: String,
  totalServiceTimeMillis: String,
  readServicTimeMillis: String,
  writeServiceTimeMillis: String,
  delAckPct: String,
  ssdReadBandwidthMBPS: String,
  ssdWriteBandwidthMBPS: String,
  ssdReadservicewidthMBPS: String,
  ssdWriteServiceTimeMillis: String,
  cpuAvgMax: String,
  updated_date: { type: Date, default: Date.now },
});

module.exports = mongoose.model('System', SystemSchema);